#!/bin/bash

sudo apt-get update -qq && sudo apt-get install -qq curl && sudo apt-get install -qq git
sudo apt-get install -y pkg-config
curl -O https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.10.1.linux-amd64.tar.gz
rm go1.10.1.linux-amd64.tar.gz
echo "export PATH=\$PATH:/usr/local/go/bin" >> ~.bashrc
echo "export GOPATH=\$HOME/go" >> ~./bashrc
echo "export GOBIN=\$GOPATH/bin" >> ~./bashrc
echo "export PATH=\$PATH:\$GOBIN" >> ~./bashrc
source ~/.bashrc

go get github.com/DATA-DOG/godog/cmd/godog
go get github.com/gorilla/mux
go get github.com/sevlyar/go-daemon
go get github.com/go-sql-driver/mysql
go get github.com/multiformats/go-multihash

sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
go get -v github.com/veandco/go-sdl2/{sdl,img,mix,ttf}

go get -v github.com/sqs/goreturns
go get -v github.com/uudashr/gopkgs/cmd/gopkgs
go get -v github.com/nsf/gocode
