#!/bin/bash

sudo apt-get update -qq && sudo apt-get install -qq curl && sudo apt-get install -qq git
# sudo apt-get install -y pkg-config
curl -O https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.11.4.linux-amd64.tar.gz
rm go1.11.4.linux-amd64.tar.gz
echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
echo "export GOPATH=\$HOME/go" >> ~/.bashrc
echo "export GOBIN=\$GOPATH/bin" >> ~/.bashrc
echo "export PATH=\$PATH:\$GOBIN" >> ~/.bashrc

echo "if [[ \$(ps aux | grep -c ssh-agent) -ne 2 ]]; then
	eval \"\$(ssh-agent -s)\"
	ssh-add ~/.ssh/id
	echo \"Knock, knock, $USER.\"
else
	echo \"Follow the white rabbit.\"
fi" >> ~/.bashrc

source ~/.bashrc

go get github.com/DATA-DOG/godog/cmd/godog
go get github.com/gorilla/mux
# go get github.com/sevlyar/go-daemon
go get github.com/go-sql-driver/mysql
go get github.com/multiformats/go-multihash
go get github.com/ipfs/go-ipfs

ipfs init
ipfs daemon&

go get -u github.com/whyrusleeping/gx-go
go get -u github.com/whyrusleeping/gx
cd $GOPATH/src/github.com/ipfs/go-ipfs
gx i
# sudo apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
# go get -v github.com/veandco/go-sdl2/{sdl,img,mix,ttf}

# go get -v github.com/sqs/goreturns
# go get -v github.com/uudashr/gopkgs/cmd/gopkgs
# go get -v github.com/nsf/gocode

